### ISSUE TITLE
Caravans not moving/eating any more since update from 1.6.0 to 1.6.1

### ISSUE THREAD

**Issue by gbl** [Vectorial1024/Desynchronized#25]
This is on a game I've been playing for a while now, the ingame date is Aprimay 6th, 5503.
Desynchronized had been installed from the beginning of this game. Should have been 1.6.0 as I'm using the steam workshop and have autoupdate enabled.
Today, when I started RimWorld, I got the message that Desynchronized updated to 1.6.1. Then, when I started sending caravans, they got stuck immediately after leaving the colony map, not moving and not eating anymore (leading to starvation after a short time). When I tell the caravan to enter the colony on the world map, they do so immediately, so it seems they really didn't move at all.
I did not see this behaviour when Desynchronized was on 1.6.0.

After removing Desynchronized from the mod list, and ignoring the warning when loading the game, caravans behave normally again.

Edit: As soon as caravans are (or should be ...) on their way, the debug log fills with this error message:

```

System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.PawnRelationUtility+<GetRelations>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0 
  at RimWorld.PawnRelationUtility.GetMostImportantRelation (Verse.Pawn me, Verse.Pawn other) [0x00000] in <filename unknown>:0 
  at Desynchronized.TNDBS.Utilities.NewsImportanceExtensionHelper.GetSocialProximityScoreForOther (Verse.Pawn subject, Verse.Pawn other) [0x00000] in <filename unknown>:0 
  at Desynchronized.TNDBS.TaleNewsPawnDied.CalculateNewsImportanceForPawn (Verse.Pawn pawn, Desynchronized.TNDBS.TaleNewsReference reference) [0x00000] in <filename unknown>:0 
  at Desynchronized.TNDBS.TaleNewsReference.RecalculateNewsImportance () [0x00000] in <filename unknown>:0 
  at Desynchronized.TNDBS.TaleNewsReference.get_CachedNewsImportance () [0x00000] in <filename unknown>:0 
  at Desynchronized.TNDBS.TaleNewsDatabase.UpdateForgetStatus () [0x00000] in <filename unknown>:0 
  at Desynchronized.TNDBS.TaleNewsDatabase.Tick () [0x00000] in <filename unknown>:0 
  at RimWorld.Planet.WorldObjectsHolder.WorldObjectsHolderTick () [0x00000] in <filename unknown>:0 
  at RimWorld.Planet.World.WorldTick () [0x00000] in <filename unknown>:0 
  at Verse.TickManager.DoSingleTick () [0x00000] in <filename unknown>:0 
Verse.Log:Error(String, Boolean)
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

```

Maybe the change from 1.6.0 to 1.6.1 removed this problem from the "normal" game, but didn't fix it in caravan mode, so it's still there but worse because some "make it right when it's wrong" code from the normal game doesn't get run anymore?

**Comment by Vectorial1024** [comment]
**Problem Analysis**

All `WorldObject`s shall be ticked by `TickManager` regularly during the game. Both the `TaleNewsDatabase` (our problematic guest) and `Caravan` (our victim) are `WorldObject`s.

Here is what the list of `WorldObject` will look like in theory; `TickManager` will tick `WorldObject`s from the beginning of the list till the end:

```
[beginning of list]
[...]
Desynchronized.TNDBS.TaleNewsDatabase <- Created from save-file data during loading phase
[...]
RimWorld.Planet.Caravan <- Created from player action of "send caravan"
[end of list]
```

If there are errors when trying to tick the `TaleNewsDatabase` (this error), then control will immediately go back to the `TaleManager` to print the error message (the one you included above). However, `Caravan` ticking will be skipped, so pawns will stand still and die.

It's a reasonable issue.

**Follow-up**

The problem then becomes finding the source of error when ticking the `TaleNewsDatabase`. After clearing that error, the `Caravan` will be ticked successfully, and pawns will not starve to death.

Now that becomes another problem...

**Comment by gbl** [comment]
I don't know much about C# as I'm a java person, but can't you do something like

```
try {
    do whatever Desynchronized.TNDBS.TaleNewsDatabase.Tick is doing currently
} catch (NullReferenceException ex) {
    // nothing
}
```

in the Desynchronized.TNDBS.TaleNewsDatabase.Tick method? That way, if anything goes wroing in your Tick(), at least it shouldn't affect the rest of World object ticking.

**Comment by Vectorial1024** [comment]
In fact, the syntax for exception handling in Java and C# are exactly the same, just that the exception names are different. We have `NullPointerException` in Java, but `NullReferenceException` in C#, both are about accessing a null object.

Yeah, we should add in the try-catch block in the `TaleNewsDatabase` ticking code. While it doesn't really solve anything, at least other components are not affected.

I'm leaving this issue open until I can find and fix the underlying error.

**Comment by Vectorial1024** [comment]
Cannot reproduce and no more reports, so closed.
