### ISSUE TITLE
[1.6.1] All thought are broken

### ISSUE THREAD

**Issue by Mihokyo** [Vectorial1024/Desynchronized#26]
From harvesting to kidnapped/killed lover. We can all see them in the tale news, but nothing in thought.

Exemple:
I make game with 2 guys, 1 man and girl fiancées.
I force the girl to kill her fiancé.

She didn't get the thought about her fiancé died. But we can see it in the tale-news of the girl

1 guys harvest prisoner. No bad thought to for the harvester

**Comment by Vectorial1024** [comment]
I have a father, a son, and an outsider in the same map. Then I told the outsider to kill the son. When the son died, the father has "my son died" + "witnessed family member's death" in the thoughts list.

Perhaps the issue is solved in the v1.6.2 in my computer (not released yet).

**Comment by Vectorial1024** [comment]
Cannot reproduce and no more reports, so closed.
