### ISSUE TITLE
Duplicate translation should be removed

### ISSUE THREAD

**Issue by alextd** [Vectorial1024/Desynchronized#27]
Kinda silly that the only translation string in Desync_Letters.xml is already in Vanilla:
( <Kidnapped>Kidnapped</Kidnapped> )

 Duplicate keyed translation key: Kidnapped in language English

**Comment by Vectorial1024** [comment]
It's quite unexpected; the string is in ITabs -> Social Tab -> Kidnapped.

Now, we just need to see if that vanilla translation key match the grammar of our side to see if we need to change our translation key.

**Comment by Vectorial1024** [comment]
Alright! Will be removing the duplicate translation string in v1.6.3.
