### ISSUE TITLE
Error with UpdateFeatureBase name also used by other mods.

### ISSUE THREAD

**Issue by jptrrs** [Vectorial1024/Desynchronized#29]
Hi! There's an error when this mod is loaded alongside DefensivePositions, I pasted it below.
I was facing the same issue on two of my mods, maybe we followed the same [insufficient instructions from the HugsLib creator ](https://github.com/UnlimitedHugs/RimworldHugsLib/wiki/HugsLib-7.0-for-Rimworld-1.1-update-guide). He recommended copying the "UpdateFeatureDefs" folder to the new "News" folder, but there's more to it. It seems those defs are now shared beween all mods, so each mod that declares an abstract def named "UpdateFeatureBase" would be trying to overwrite the other. It can be easily solved by renaming it to something like "Desynchronized.UpdateFeatureBase", for instance.
I just thought I could share what I have learned.

XML error: Could not register node named "UpdateFeatureBase" because this name is already used.
Verse.Log:Error(String, Boolean)
Verse.XmlInheritance:TryRegister(XmlNode, ModContentPack)
HugsLib.News.UpdateFeatureDefLoader:LoadAndParseNewsFeatureDefs()
HugsLib.News.UpdateFeatureDefLoader:ReloadNewsFeatureDefs()
HugsLib.News.UpdateFeatureManager:OnStaticConstructorInit()
HugsLib.HugsLibController:LateInitialize()
HugsLib.Core.StaticInitializer:.cctor()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
Verse.StaticConstructorOnStartupUtility:CallAll()
Verse.<>c:<DoPlayLoad>b__4_2()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:DMD<DMD<Update_Patch1>?-1439903744::Update_Patch1>(Root)
Verse.Root_Entry:Update()

**Comment by Vectorial1024** [comment]
Thanks for reporting!

I actually also encountered this problem when, a while ago, two of my mods could not load the news XML. I originally thought it may be due to me not paying close attention to the documentation but renamed the news defs to other names just in case.

Now I am convinced we really need to rename the defs to other names. Will come back to this later.

**Comment by jptrrs** [comment]
Yeah, from what I gathered all those must have unique names: the file
itself, the abstract def attribute and the defName.

João Pedro

**Comment by Vectorial1024** [comment]
It has now been fixed! Closing.
