### ISSUE TITLE
Correct thoughts given to wrong map when Colonists die

### ISSUE THREAD

**Issue by Mihokyo** [Vectorial1024/Desynchronized#3]
I got 2 city, and play in multiplayer from zetrith. I don't know if its cause of it

Some one guys have call to be save in the second city, i told yes.. he join and because he got bad burn as stat i lets him die, when he die the bad perk "Colonist die" go in the main city

**Comment by Vectorial1024** [comment]
I am not sure what you mean.

Do you mean you did a "incapacitated refugee quest"? In that quest, the person you rescue is supposed to join your faction, and hence will become a colonist. When you let him die, the people that you sent to rescue the dead person will get the "Colonist died" bad perk. Then, when these people come back home, they will spread the news, and everyone will eventually get that bad perk. This is by design.

Or do you mean something else?

**Comment by Mihokyo** [comment]
Hello, sorry for the first answer. 👎  for me

I mean, nobody came to rescue the refugee and the refugee was killed at the beginning of the raid. So in the colony where he came(SecondaryColonie), nobody get "Colonist died" because nobody know about that. But in the MainColonie, all the colons had this bad perk.  
__________

**Where did the refugee call & die:**
SecondaryColonie.
___________
**Where people got bad perk/thoughts:**
MainColonie.
___________
**Event was:**  
(https://rimworldwiki.com/wiki/Events#Refugee_Chased_at_.28Settlement.29)

**Bad perk (Thoughts):**
(https://rimworldwiki.com/wiki/Thoughts#Colonist_died)
Map:

<a href="https://www.noelshack.com/2019-11-3-1552500341-rimexplain.png"><img src="https://image.noelshack.com/minis/2019/11/3/1552500341-rimexplain.png" border="0" alt="1552500341-rimexplain.png - envoi d'image avec NoelShack" title="1552500341-rimexplain.png"/></a>
________

I hope that i'ts more obvious this time ! :p

**Comment by Vectorial1024** [comment]
Many thanks for the info! It has become much clearer now.

I will look into it.

**Comment by Vectorial1024** [comment]
It's been a while.

I currently do not use the Zetrith Multiplayer mod. And I also cannot find any error in my test environment. Hence, it should be something caused by Zetrith's Multiplayer mod.

 Perhaps I will come back to this once other features are complete.

**Comment by Vectorial1024** [comment]
Self-note: Zetrith's Multiplayer mod may be abandoned. Parexy's Multiplayer claims to be the successor of Zetrith's Multiplayer. Make sure to check the names carefully when beginning to address this problem.

**Comment by Vectorial1024** [comment]
Now that Parexy's Multiplayer mod seem to become official (https://steamcommunity.com/sharedfiles/filedetails/?id=1752864297), does this error still persist when using Parexy's multiplayer mod?

**Comment by Mihokyo** [comment]
Hello

I didn't see this error again with Parexy's multiplayer. And god know how much time i did this with my partner @Azuhiko

I didn't remember exactly how the guys was dead when the bug come. 
IF
By instadead *headshot*
OR
By Bloodlost

Maybe i need to try more by insta dead but it happen uncommon

**Comment by Mihokyo** [comment]
Maybe it has link with familly link in #6 , then someone got in other city "Oh my uncle is dead" and spread that into the city so they all get "Colonist die"

**Comment by Vectorial1024** [comment]
I heard that Zetrith abandoned his work midway and disappeared, so perhaps his version may have bugs. Still, Parexy's version should have fixed the bugs by now.

Thank you for investigating this issue! Eventually, I will have to implement a UI to let us see the Tale-News in-game, so we can see the spread easily and debug easily.

I assume this is a false alarm for now.
