### ISSUE TITLE
Bug TNDBS.TaleNewsPawnDied 

### ISSUE THREAD

**Issue by Mihokyo** [Vectorial1024/Desynchronized#8]
https://dpaste.de/qsfe

I will try to look in source, but I'm not sure to understanding !

**Comment by Vectorial1024** [comment]
This is a known issue on Steam, but I forgot to add an entry here. Thanks for the help!

I have already found a solution to this problem. The fix will come out in the next update.

**Comment by Vectorial1024** [comment]
The issue is not over yet, since I am still testing my solution.

**Comment by Vectorial1024** [comment]
Fix is confirmed to be working fine. Closing for real.

**Comment by Vectorial1024** [comment]
The bug is fixed in the latest release (v1.5.0).
